// <auto-generated />
// Generated from Pokemon-XD-Code/Objects/scripts/XD/XGScriptClassFunctionsData.swift.
#nullable enable
using System.Collections.ObjectModel;

namespace CipherSnagemEditor.Core.GameCube;

internal sealed record GameCubeScriptFunctionInfo(
    int ClassId,
    string ClassName,
    int FunctionId,
    string Name,
    int ParameterCount,
    string ParameterTypes,
    string ReturnType,
    string Hint)
{
    public string QualifiedName => $"{ClassName}.{Name}";

    public string LegacyName => $"class_{ClassId}.function_{FunctionId}";
}

internal static class GameCubeScriptCatalog
{
    public static IReadOnlyDictionary<int, string> ClassNames { get; } = new ReadOnlyDictionary<int, string>(new Dictionary<int, string>
    {
        [0] = "Standard",
        [4] = "Vector",
        [5] = "Matrix",
        [6] = "Object",
        [7] = "Array",
        [33] = "Camera",
        [35] = "Character",
        [37] = "Pokemon",
        [38] = "Map",
        [39] = "Tasks",
        [40] = "Menu",
        [41] = "Transition",
        [42] = "Battle",
        [43] = "Player",
        [44] = "Light",
        [45] = "Model",
        [46] = "Collision",
        [47] = "Sound",
        [48] = "Controller",
        [49] = "PDA",
        [50] = "Direction",
        [51] = "TV",
        [52] = "Daycare",
        [54] = "Thread",
        [58] = "Move",
        [59] = "ShadowPokemon",
        [60] = "Pokespot",
    });

    private static readonly IReadOnlyDictionary<(int ClassId, int FunctionId), GameCubeScriptFunctionInfo> FunctionsById = new ReadOnlyDictionary<(int ClassId, int FunctionId), GameCubeScriptFunctionInfo>(new Dictionary<(int ClassId, int FunctionId), GameCubeScriptFunctionInfo>
    {
        [(0, 17)] = new(0, "Standard", 17, "pause", 1, "[.float]", ".null", ""),
        [(0, 18)] = new(0, "Standard", 18, "yield", 1, "[.integer]", ".null", ""),
        [(0, 19)] = new(0, "Standard", 19, "setTimer", 1, "nil", ".null", ""),
        [(0, 20)] = new(0, "Standard", 20, "getTimer", 1, "nil", "nil", ""),
        [(0, 21)] = new(0, "Standard", 21, "waitUntil", 2, "nil", ".null", ""),
        [(0, 22)] = new(0, "Standard", 22, "printString", 1, "[.string]", ".null", ""),
        [(0, 28)] = new(0, "Standard", 28, "convertShortToInt", 1, "[.integer]", ".integer", ""),
        [(0, 29)] = new(0, "Standard", 29, "getTypeName", 1, "[.anyType]", ".string", ""),
        [(0, 30)] = new(0, "Standard", 30, "getCharacterAtIndex", 2, "[.string, .integerIndex]", ".integer", ""),
        [(0, 31)] = new(0, "Standard", 31, "copyString", 1, "[.string]", ".string", ""),
        [(0, 32)] = new(0, "Standard", 32, "findSubstring", 2, "[.string, .string]", ".invalid", "always returns -1"),
        [(0, 33)] = new(0, "Standard", 33, "setBit", 2, "[.integer, .integerIndex]", ".integer", ""),
        [(0, 34)] = new(0, "Standard", 34, "clearBit", 2, "[.integer, .integerIndex]", ".integer", ""),
        [(0, 35)] = new(0, "Standard", 35, "orBits", 2, "[.integer, .integer]", ".integer", ""),
        [(0, 36)] = new(0, "Standard", 36, "nandBits", 2, "[.integer, .integer]", ".integer", ""),
        [(0, 48)] = new(0, "Standard", 48, "sin", 1, "[.integerAngleDegrees]", ".float", ""),
        [(0, 49)] = new(0, "Standard", 49, "cos", 1, "[.integerAngleDegrees]", ".float", ""),
        [(0, 50)] = new(0, "Standard", 50, "tan", 1, "[.integerAngleDegrees]", ".float", ""),
        [(0, 51)] = new(0, "Standard", 51, "atan2", 1, "[.float]", ".integer", ""),
        [(0, 52)] = new(0, "Standard", 52, "acos", 1, "[.float]", ".integerAngleDegrees", ""),
        [(0, 53)] = new(0, "Standard", 53, "sqrt", 1, "[.float]", ".float", ""),
        [(0, 129)] = new(0, "Standard", 129, "setFlagToTrue", 1, "[.flag]", ".null", ""),
        [(0, 130)] = new(0, "Standard", 130, "setFlagToFalse", 1, "[.flag]", ".null", ""),
        [(0, 131)] = new(0, "Standard", 131, "setFlag", 2, "[.flag, .integer]", ".null", ""),
        [(0, 132)] = new(0, "Standard", 132, "isFlagSet", 2, "[.flag, .integer]", ".bool", ""),
        [(0, 133)] = new(0, "Standard", 133, "getFlag", 1, "[.flag]", ".integer", ""),
        [(0, 136)] = new(0, "Standard", 136, "printf", 1, "[.string, .optional(.list(.anyType))]", ".null", "debug only"),
        [(0, 137)] = new(0, "Standard", 137, "genRandomNumberMod", 1, "[.integer]", ".integer", "from 0 to n - 1"),
        [(0, 138)] = new(0, "Standard", 138, "setShadowPokemonStatus", 2, "[.shadowID, .shadowStatus]", ".null", ""),
        [(0, 139)] = new(0, "Standard", 139, "checkAllFlagsAreTrue", 1, "[.array(.flag)]", ".bool", ""),
        [(0, 140)] = new(0, "Standard", 140, "checkAtLeastOneFlagIsTrue", 1, "[.array(.flag)]", ".bool", ""),
        [(0, 142)] = new(0, "Standard", 142, "syncTaskFromCommonScript", 3, "[.scriptFunction, .integer, .list(.anyType)]", ".null", ""),
        [(0, 143)] = new(0, "Standard", 143, "setScriptDebugVisibility", 1, "[.bool]", ".null", "doesn't work on release builds but can be shown via modding"),
        [(0, 145)] = new(0, "Standard", 145, "mapSetCharacterCollision", 1, "[.bool]", ".null", ""),
        [(0, 146)] = new(0, "Standard", 146, "mapGetCharacterCollision", 0, "[]", ".bool", ""),
        [(0, 147)] = new(0, "Standard", 147, "setTreasureInteractionRange", 2, "[.integer, .float]", "nil", ""),
        [(0, 148)] = new(0, "Standard", 148, "getStringWithID", 1, "[.msg]", ".string", ""),
        [(0, 149)] = new(0, "Standard", 149, "getTreasureBoxCharacter", 1, "[.treasureID]", ".objectName(\"Character\")", "gets the character object"),
        [(0, 150)] = new(0, "Standard", 150, "pokemonSpeciesGetNameID", 1, "[.pokemon]", ".msg", ""),
        [(0, 151)] = new(0, "Standard", 151, "getArrayElement", 1, "[.array(.anyType), .arrayIndex]", ".anyType", ""),
        [(0, 152)] = new(0, "Standard", 152, "isHMMove", 1, "[.move]", ".bool", ""),
        [(0, 153)] = new(0, "Standard", 153, "distanceBetween", 2, "[.vector, .vector]", ".float", "between 2 points given by vectors"),
        [(0, 154)] = new(0, "Standard", 154, "getCharacterID", 1, "[.objectName(\"Character\")]", ".integer", ""),
        [(0, 155)] = new(0, "Standard", 155, "startGlow", 6, "[.float, .integer, .bool, .bool, .bool, .integer]", ".null", ""),
        [(0, 156)] = new(0, "Standard", 156, "stopGlow", 0, "[]", ".null", ""),
        [(0, 157)] = new(0, "Standard", 157, "setLensFlare", 5, "[.integer, .float, .float, .float, .float]", ".null", ""),
        [(0, 158)] = new(0, "Standard", 158, "getCharacterObjectWithIndex", 1, "[.integer]", ".objectName(\"Character\")", ""),
        [(0, 159)] = new(0, "Standard", 159, "getFrameRate", 0, "[]", ".integer", ""),
        [(0, 160)] = new(0, "Standard", 160, "getRegion", 0, "[]", ".region", ""),
        [(0, 161)] = new(0, "Standard", 161, "getLanguage", 0, "[]", ".language", ""),
        [(4, 3)] = new(4, "Vector", 3, "toString", 1, "[.vector]", ".string", ""),
        [(4, 16)] = new(4, "Vector", 16, "clear", 1, "[.vector]", ".vector", ""),
        [(4, 17)] = new(4, "Vector", 17, "normalize", 1, "[.vector]", ".vector", ""),
        [(4, 18)] = new(4, "Vector", 18, "set", 3, "[.vector, .float, .float, .float]", ".null", "vec, x, y, z"),
        [(4, 19)] = new(4, "Vector", 19, "set2", 4, "[.vector, .float, .float, .float, nil]", ".null", "vec, x, y, z"),
        [(4, 20)] = new(4, "Vector", 20, "fill", 2, "[.vector, .float]", ".null", "set x,y & z to the same value"),
        [(4, 21)] = new(4, "Vector", 21, "abs", 1, "[.vector]", ".null", "set each dimension to its magnitude"),
        [(4, 22)] = new(4, "Vector", 22, "negate", 1, "[.vector]", ".null", ""),
        [(4, 23)] = new(4, "Vector", 23, "isZero", 1, "[.vector]", ".bool", ""),
        [(4, 24)] = new(4, "Vector", 24, "crossProduct", 2, "[.vector, .vector]", ".vector", ""),
        [(4, 25)] = new(4, "Vector", 25, "dotProduct", 2, "[.vector, .vector]", ".float", ""),
        [(4, 26)] = new(4, "Vector", 26, "magnitude", 1, "[.vector]", ".float", ""),
        [(4, 27)] = new(4, "Vector", 27, "squaredMagnitude", 1, "[.vector]", ".float", ""),
        [(4, 28)] = new(4, "Vector", 28, "angle", 2, "[.vector]", ".float", ""),
        [(7, 3)] = new(7, "Array", 3, "toString", 1, "[.array(.anyType)]", ".string", ""),
        [(7, 16)] = new(7, "Array", 16, "get", 2, "[.array(.anyType), .arrayIndex]", ".anyType", ""),
        [(7, 17)] = new(7, "Array", 17, "set", 3, "[.array(.anyType), .arrayIndex, .anyType]", ".null", ""),
        [(7, 18)] = new(7, "Array", 18, "length", 1, "[.array(.anyType)]", ".integer", ""),
        [(7, 19)] = new(7, "Array", 19, "resize", 2, "[.array(.anyType), .integer]", ".null", ""),
        [(7, 20)] = new(7, "Array", 20, "extend", 2, "[.array(.anyType), .integer]", ".null", ""),
        [(7, 22)] = new(7, "Array", 22, "resetIterator", 1, "[.array(.anyType)]", ".null", ""),
        [(7, 23)] = new(7, "Array", 23, "derefIterator", 2, "[.array(.anyType), nil]", ".null", ""),
        [(7, 24)] = new(7, "Array", 24, "getIteratorPos", 2, "[.array(.anyType), nil]", ".integer", ""),
        [(7, 25)] = new(7, "Array", 25, "append", 2, "[.array(.anyType), .anyType]", ".null", ""),
        [(33, 16)] = new(33, "Camera", 16, "setDefaultForMap", 4, "[.objectName(\"Camera\"), .number, .number, .number]", ".null", ""),
        [(33, 17)] = new(33, "Camera", 17, "setCameraType", 3, "[.objectName(\"Camera\"), .cameraType]", ".null", ""),
        [(33, 18)] = new(33, "Camera", 18, "followCharacter", 2, "[.objectName(\"Camera\"), .objectName(\"Character\")]", ".null", ""),
        [(33, 19)] = new(33, "Camera", 19, "setTargetPosition", 4, "[.objectName(\"Camera\"), .number, .number, .number]", ".null", "(x, y, z)"),
        [(33, 20)] = new(33, "Camera", 20, "setTargetPositionVector", 2, "[.objectName(\"Camera\"), .vector]", ".null", "<x, y, z>"),
        [(33, 21)] = new(33, "Camera", 21, "setTargetPositionOffset", 4, "[.objectName(\"Camera\"), .number, .number, .number]", ".null", "(x, y, z)"),
        [(33, 22)] = new(33, "Camera", 22, "setTargetPositionOffsetVector", 2, "[.objectName(\"Camera\"), .vector]", ".null", "<x, y, z>"),
        [(33, 23)] = new(33, "Camera", 23, "setPosition", 4, "[.objectName(\"Camera\"), .number, .number, .number]", ".null", "(x, y, z)"),
        [(33, 24)] = new(33, "Camera", 24, "setPositionVector", 2, "[.objectName(\"Camera\"), .vector]", ".null", "<x, y, z>"),
        [(33, 25)] = new(33, "Camera", 25, "setRotationRadians", 4, "[.objectName(\"Camera\"), .number, .number, .number]", ".null", "rotation about each of the axes (x, y, z) in radians"),
        [(33, 26)] = new(33, "Camera", 26, "setRotationRadiansVector", 2, "[.objectName(\"Camera\"), .vector]", ".null", "rotation about each of the axes <x, y, z> in radians"),
        [(33, 27)] = new(33, "Camera", 27, "playAnimationFromFile", 5, "[.objectName(\"Camera\"), .integer, .camIdentifier, .integer, .integer]", ".null", "from .cam file in fsys with gid"),
        [(33, 28)] = new(33, "Camera", 28, "stopAnimation", 1, "[.objectName(\"Camera\")]", ".null", ""),
        [(33, 29)] = new(33, "Camera", 29, "pauseAnimation", 1, "[.objectName(\"Camera\")]", ".null", ""),
        [(33, 30)] = new(33, "Camera", 30, "resumeAnimation", 1, "[.objectName(\"Camera\")]", ".null", ""),
        [(33, 31)] = new(33, "Camera", 31, "awaitAnimation", 2, "[.objectName(\"Camera\"), .bool]", ".null", "wait until the animation finishes?"),
        [(33, 32)] = new(33, "Camera", 32, "setAnimationSpeed", 2, "[.objectName(\"Camera\"), .number]", ".null", ""),
        [(33, 33)] = new(33, "Camera", 33, "moveTargetCharacter", 5, "[.objectName(\"Camera\"), .objectName(\"Character\"), .cameraType, .number, .number]", ".null", ""),
        [(33, 34)] = new(33, "Camera", 34, "moveToTarget", 6, "[.objectName(\"Camera\"), .cameraType, .number, .number, .number, .number]", ".null", ""),
        [(33, 35)] = new(33, "Camera", 35, "moveToTargetVector", 6, "[.objectName(\"Camera\"), .vector, .cameraType, .number, .number]", ".null", ""),
        [(33, 36)] = new(33, "Camera", 36, "moveToPosition", 7, "[.objectName(\"Camera\"), .cameraType, .number, .number, .number, .number, .number]", ".null", ""),
        [(33, 37)] = new(33, "Camera", 37, "moveToPositionVector", 5, "[.objectName(\"Camera\"), .vector, .cameraType, .number, .number]", ".null", ""),
        [(33, 38)] = new(33, "Camera", 38, "moveToRotation", 7, "[.objectName(\"Camera\"), .cameraType, .number, .number, .number, .number, .number]", ".null", ""),
        [(33, 39)] = new(33, "Camera", 39, "moveToRotationVector", 5, "[.objectName(\"Camera\"), .vector, .cameraType, .number, .number]", ".null", ""),
        [(33, 40)] = new(33, "Camera", 40, "isCameraDoneMoving", 2, "[.objectName(\"Camera\"), .number]", ".bool", ""),
        [(33, 41)] = new(33, "Camera", 41, "setHeight", 2, "[.objectName(\"Camera\"), .number]", ".null", ""),
        [(33, 42)] = new(33, "Camera", 42, "setDistance", 2, "[.objectName(\"Camera\"), .number]", ".null", ""),
        [(33, 43)] = new(33, "Camera", 43, "setYRotation", 2, "[.objectName(\"Camera\"), .number]", ".null", ""),
        [(33, 44)] = new(33, "Camera", 44, "setFieldOfView", 2, "[.objectName(\"Camera\"), .number]", ".null", "angle"),
        [(33, 45)] = new(33, "Camera", 45, "update", 1, "[.objectName(\"Camera\")]", ".null", ""),
        [(33, 46)] = new(33, "Camera", 46, "reset", 1, "[.objectName(\"Camera\")]", ".null", ""),
        [(33, 47)] = new(33, "Camera", 47, "enableDefaultForMap", 1, "[.objectName(\"Camera\")]", ".null", ""),
        [(33, 48)] = new(33, "Camera", 48, "disableDefaultForMap", 1, "[.objectName(\"Camera\")]", ".null", ""),
        [(33, 49)] = new(33, "Camera", 49, "mapCameraBlend", 2, "[.objectName(\"Camera\"), .number]", ".null", ""),
        [(33, 50)] = new(33, "Camera", 50, "getFieldOfView", 1, "[.objectName(\"Camera\")]", ".float", ""),
        [(33, 51)] = new(33, "Camera", 51, "getPosition", 1, "[.objectName(\"Camera\")]", ".vector", ""),
        [(33, 52)] = new(33, "Camera", 52, "getRotation", 1, "[.objectName(\"Camera\")]", ".vector", ""),
        [(33, 53)] = new(33, "Camera", 53, "moveToPositionVectorWithAcceleration", 5, "[.objectName(\"Camera\"), .vector, .number, .number, .number]", ".null", "position, unk, unk, acceleration"),
        [(33, 54)] = new(33, "Camera", 54, "moveToPositionWithAcceleration", 7, "[.objectName(\"Camera\"), .number, .number, .number, .number, .number, .number]", ".null", "unk, unk, unk, unk, unk, acceleration"),
        [(33, 55)] = new(33, "Camera", 55, "moveToRotationVectorWithAcceleration", 5, "[.objectName(\"Camera\"), .vector, .number, .number, .number]", ".null", ""),
        [(33, 56)] = new(33, "Camera", 56, "moveToRotationWithAcceleration", 7, "[.objectName(\"Camera\"), .number, .number, .number, .number, .number, .number]", ".null", ""),
        [(33, 57)] = new(33, "Camera", 57, "moveToTargetVectorWithAcceleration", 5, "[.objectName(\"Camera\"), .vector, .number, .number, .number]", ".null", ""),
        [(33, 58)] = new(33, "Camera", 58, "moveToTargetWithAcceleration", 7, "[.objectName(\"Camera\"), .number, .number, .number, .number, .number, .number]", ".null", ""),
        [(33, 59)] = new(33, "Camera", 59, "moveFieldOfView", 4, "[.objectName(\"Camera\"), .number, .number, .number]", ".null", ""),
        [(33, 60)] = new(33, "Camera", 60, "moveFieldOfViewWithAcceleration", 5, "[.objectName(\"Camera\"), .number, .number, .number, .number]", ".null", ""),
        [(33, 61)] = new(33, "Camera", 61, "followCharacterWithResourceId", 2, "[.objectName(\"Camera\"), .number]", ".null", ""),
        [(33, 62)] = new(33, "Camera", 62, "followCharacterWithResourceIdExt", 2, "[.objectName(\"Camera\"), .number, .number]", ".null", ""),
        [(33, 63)] = new(33, "Camera", 63, "setFollowOffset", 2, "[.objectName(\"Camera\"), .vector]", ".null", ""),
        [(35, 16)] = new(35, "Character", 16, "setVisibility", 2, "[.objectName(\"Character\"), .bool]", ".null", ""),
        [(35, 17)] = new(35, "Character", 17, "setAnimation", 4, "[.objectName(\"Character\"), .integer, .integer, .bool]", ".bool", "(animation id, unknown, loop animation)"),
        [(35, 18)] = new(35, "Character", 18, "overrideAnimation", 4, "[.objectName(\"Character\"), .integer, .integer, .bool]", ".null", "(animation id, unknown, loop animation)"),
        [(35, 19)] = new(35, "Character", 19, "stopAnimation", 1, "[.objectName(\"Character\")]", ".integer", ""),
        [(35, 20)] = new(35, "Character", 20, "awaitAnimation", 2, "[.objectName(\"Character\")]", ".bool", "wait until animation finishes?"),
        [(35, 21)] = new(35, "Character", 21, "beingDialog", 3, "[.objectName(\"Character\"), .msg, .bool]", ".null", "msgID, autoend"),
        [(35, 22)] = new(35, "Character", 22, "endDialog", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 23)] = new(35, "Character", 23, "initializeCharacterFromResourceId", 2, "[.objectName(\"Character\"), .integer]", ".bool", "resource id"),
        [(35, 24)] = new(35, "Character", 24, "deinitializeCharacter", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 25)] = new(35, "Character", 25, "isWithinBounds", 5, "[.objectName(\"Character\"), .float, .float, .float, .float]", ".bool", "(min x, min z, max x, max z) or v. versa"),
        [(35, 26)] = new(35, "Character", 26, "isWithinBoundsVector", 3, "[.objectName(\"Character\"), .vector, .vector]", ".bool", ""),
        [(35, 27)] = new(35, "Character", 27, "didStepOntoLine", 7, "[.objectName(\"Character\"), .float, .float, .float, .float, .float, .bool]", ".bool", "(min x, min z, max x, max z) or v. versa"),
        [(35, 28)] = new(35, "Character", 28, "didStepOntoLineVector", 4, "[.objectName(\"Character\"), .vector, .vector, .bool]", ".bool", ""),
        [(35, 29)] = new(35, "Character", 29, "setPosition", 4, "[.objectName(\"Character\"), .float, .float, .float]", ".null", "(x, y, z)"),
        [(35, 30)] = new(35, "Character", 30, "setPositionVector", 2, "[.objectName(\"Character\"), .vector]", ".null", ""),
        [(35, 31)] = new(35, "Character", 31, "setRotation", 4, "[.objectName(\"Character\"), .floatAngleDegrees, .floatAngleDegrees, .floatAngleDegrees]", ".null", "about each axis"),
        [(35, 32)] = new(35, "Character", 32, "setRotationVector", 2, "[.objectName(\"Character\"), .vector]", ".null", ""),
        [(35, 33)] = new(35, "Character", 33, "getPositionIntoValues", 4, "[.objectName(\"Character\"), .float, .float, .float]", ".null", "creates a vector from the args and replaces vector with character's position"),
        [(35, 34)] = new(35, "Character", 34, "getPositionIntoVector", 2, "[.objectName(\"Character\"), .vector]", ".null", "replaces the vector with the character's position"),
        [(35, 36)] = new(35, "Character", 36, "walkToPosition", 5, "[.objectName(\"Character\"), .integer, .float, .float, .float]", ".null", "(speed, x, y, z)"),
        [(35, 37)] = new(35, "Character", 37, "walkToPositionVector", 3, "[.objectName(\"Character\"), .integer, .vector]", ".null", "(speed, vector<x, y, z>)"),
        [(35, 38)] = new(35, "Character", 38, "walkToCharacter", 4, "[.objectName(\"Character\"), .objectName(\"Character\"), .float, .integer]", ".null", ""),
        [(35, 39)] = new(35, "Character", 39, "awaitAnimation", 2, "[.objectName(\"Character\"), .bool]", ".null", "(wait for completion?)"),
        [(35, 40)] = new(35, "Character", 40, "setCharacterFlags", 2, "[.objectName(\"Character\"), .integerBitMask]", ".null", ""),
        [(35, 41)] = new(35, "Character", 41, "unsetCharacterFlags", 2, "[.objectName(\"Character\"), .integerBitMask]", ".null", ""),
        [(35, 42)] = new(35, "Character", 42, "setHeadTiltTowardsPlayer", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 43)] = new(35, "Character", 43, "setHeadTiltTowardsCharacter", 2, "[.objectName(\"Character\"), .objectName(\"Character\")]", ".null", ""),
        [(35, 44)] = new(35, "Character", 44, "setHeadTiltTowardsPosition", 4, "[.objectName(\"Character\"), .integer, .integer, .integer]", ".null", ""),
        [(35, 45)] = new(35, "Character", 45, "resetHeadTilt", 2, "[.objectName(\"Character\"), .integer]", ".null", ""),
        [(35, 46)] = new(35, "Character", 46, "awaitHeadTilt", 2, "[.objectName(\"Character\"), .bool]", ".null", "wait for completion?"),
        [(35, 47)] = new(35, "Character", 47, "turnToAngleRadians", 2, "[.objectName(\"Character\"), .floatAngleRadians]", ".null", ""),
        [(35, 48)] = new(35, "Character", 48, "turnToRotation", 4, "[.objectName(\"Character\"), .float, .float, .float, .float]", ".null", "x, y, z, speed"),
        [(35, 49)] = new(35, "Character", 49, "turnToCharacter", 3, "[.objectName(\"Character\"), .objectName(\"Character\"), .float]", ".null", "(speed)"),
        [(35, 50)] = new(35, "Character", 50, "setMovementSpeed", 2, "[.objectName(\"Character\"), .float]", ".null", "speed"),
        [(35, 51)] = new(35, "Character", 51, "attachToCharacter", 3, "[.objectName(\"Character\"), .objectName(\"Character\"), .integer]", ".null", "mode"),
        [(35, 52)] = new(35, "Character", 52, "detachFromCharacter", 2, "[.objectName(\"Character\"), .integer]", ".null", ""),
        [(35, 53)] = new(35, "Character", 53, "yield", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 54)] = new(35, "Character", 54, "initializeNewWalkingRoute", 2, "[.objectName(\"Character\"), .integer]", ".null", "number of waypoints"),
        [(35, 55)] = new(35, "Character", 55, "addToWalkingRoute", 4, "[.objectName(\"Character\"), .float, .float, .float]", ".null", "(x, y, z)"),
        [(35, 56)] = new(35, "Character", 56, "beginWalkingRoute", 2, "[.objectName(\"Character\"), .bool]", ".null", ""),
        [(35, 57)] = new(35, "Character", 57, "deinitializeWalkingRoute", 1, "[.objectName(\"Character\")]", ".bool", ""),
        [(35, 58)] = new(35, "Character", 58, "beginInteraction", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 59)] = new(35, "Character", 59, "endInteraction", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 60)] = new(35, "Character", 60, "dropFromCeilingAppearance", 2, "[.objectName(\"Character\"), .float]", ".null", ""),
        [(35, 61)] = new(35, "Character", 61, "surprisedAnimation", 2, "[.objectName(\"Character\"), .bool]", ".null", "(don't face player?)"),
        [(35, 62)] = new(35, "Character", 62, "setCanCollide", 2, "[.objectName(\"Character\"), .bool]", ".null", "(whether the hitbox is enabled or not)"),
        [(35, 63)] = new(35, "Character", 63, "checkIfCanSeePlayer", 1, "[.objectName(\"Character\")]", ".bool", ""),
        [(35, 64)] = new(35, "Character", 64, "setAnimationBlend", 4, "[.objectName(\"Character\"), .integer, .integer, .integer]", ".bool", ""),
        [(35, 65)] = new(35, "Character", 65, "awaitAnimationBlend", 4, "[.objectName(\"Character\"), .bool]", ".bool", "wait for completion?"),
        [(35, 66)] = new(35, "Character", 66, "pauseWalking", 4, "[.objectName(\"Character\"), .bool]", ".bool", ""),
        [(35, 67)] = new(35, "Character", 67, "tiltHeadTowardsPositionVector", 2, "[.objectName(\"Character\"), .vector]", ".null", ""),
        [(35, 68)] = new(35, "Character", 68, "turnToRotationVector", 3, "[.objectName(\"Character\"), .vector, .float]", ".null", "<x, y, z>, speed"),
        [(35, 69)] = new(35, "Character", 69, "addToWalkingRouteVector", 2, "[.objectName(\"Character\"), .vector]", ".null", ""),
        [(35, 70)] = new(35, "Character", 70, "setModel", 2, "[.objectName(\"Character\"), .model]", ".null", "fsys identifier"),
        [(35, 71)] = new(35, "Character", 71, "checkIfRunning", 1, "[.objectName(\"Character\")]", ".bool", ""),
        [(35, 72)] = new(35, "Character", 72, "getMovementSpeed", 2, "[.objectName(\"Character\")]", ".floatFraction", "between 0.0 and 1.0"),
        [(35, 73)] = new(35, "Character", 73, "talk", 3, "[.objectName(\"Character\"), .talk, .msg, .optional(.variableType), .optional(.variableType)]", ".anyType", ""),
        [(35, 74)] = new(35, "Character", 74, "attachToCharacterGIRI", 4, "[.objectName(\"Character\"), .integer, .integer, .integer]", ".null", "gid, rid, mode"),
        [(35, 75)] = new(35, "Character", 75, "getPosition", 1, "[.objectName(\"Character\")]", ".vector", ""),
        [(35, 76)] = new(35, "Character", 76, "getRotation", 1, "[.objectName(\"Character\")]", ".float", ""),
        [(35, 77)] = new(35, "Character", 77, "setIdleAnimation", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 78)] = new(35, "Character", 78, "unsetIdleAnimation", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 79)] = new(35, "Character", 79, "turnToAngleDegrees", 2, "[.objectName(\"Character\"), .floatAngleDegrees, .float]", ".null", ""),
        [(35, 80)] = new(35, "Character", 80, "turnHeadByAngle", 4, "[.objectName(\"Character\"), .float, .float, .float]", ".null", ""),
        [(35, 81)] = new(35, "Character", 81, "turnHeadTowardsTarget", 3, "[.objectName(\"Character\"), .objectName(\"Character\"), .float]", ".null", ""),
        [(35, 82)] = new(35, "Character", 82, "turnHeadTowardsPlayer", 2, "[.objectName(\"Character\"), .float]", ".null", ""),
        [(35, 83)] = new(35, "Character", 83, "turnHeadTowardsWorldAngle", 4, "[.objectName(\"Character\"), .float, .float, .float]", ".null", ""),
        [(35, 84)] = new(35, "Character", 84, "turnHeadTowardsPosition", 5, "[.objectName(\"Character\"), .integer, .integer, .integer, .float]", ".null", ""),
        [(35, 85)] = new(35, "Character", 85, "getYRotationDegrees", 1, "[.objectName(\"Character\")]", ".null", "looks like it doesn't return the value so possibly unused"),
        [(35, 87)] = new(35, "Character", 87, "setToDefaultAnimation", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 88)] = new(35, "Character", 88, "setAnimationOverride", 1, "[.objectName(\"Character\")]", ".null", "Can then set a custom animation after"),
        [(35, 89)] = new(35, "Character", 89, "setWalkingRouteArray", 2, "[.objectName(\"Character\"), .array(.anyType)]", ".null", ""),
        [(35, 90)] = new(35, "Character", 90, "resetWalkingRouteArray", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 91)] = new(35, "Character", 91, "setSlowdownOn", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 92)] = new(35, "Character", 92, "setSlowdownOff", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 93)] = new(35, "Character", 93, "blinkOnce", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 94)] = new(35, "Character", 94, "startBlinking", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 95)] = new(35, "Character", 95, "stopBlinking", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 96)] = new(35, "Character", 96, "startMouthMovements", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 97)] = new(35, "Character", 97, "stopMouthMovements", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 98)] = new(35, "Character", 98, "setTalkingDistance", 2, "[.objectName(\"Character\"), .float]", ".null", ""),
        [(35, 99)] = new(35, "Character", 99, "getTalkingDistance", 1, "[.objectName(\"Character\")]", ".null", "looks like it doesn't return the value so possibly unused"),
        [(35, 100)] = new(35, "Character", 100, "startWalkingRouteStrict", 2, "[.objectName(\"Character\"), .float]", ".null", ""),
        [(35, 101)] = new(35, "Character", 101, "useHealingMachine", 3, "[.objectName(\"Character\"), .datsIdentifier, .array(.integer), .array(.integer)]", ".null", ""),
        [(35, 102)] = new(35, "Character", 102, "pauseWalkTalkMode", 2, "[.objectName(\"Character\"), .bool]", ".null", ""),
        [(35, 103)] = new(35, "Character", 103, "setAnimationSpeed", 2, "[.objectName(\"Character\"), .float]", ".null", ""),
        [(35, 104)] = new(35, "Character", 104, "setWalkingSpeed", 3, "[.objectName(\"Character\"), .float, .integer]", ".null", ""),
        [(35, 105)] = new(35, "Character", 105, "setBoundsCheck", 2, "[.objectName(\"Character\"), .integer]", ".null", ""),
        [(35, 106)] = new(35, "Character", 106, "setMotionEnded", 3, "[.objectName(\"Character\"), .integer, .bool]", ".null", ""),
        [(35, 107)] = new(35, "Character", 107, "attachParticleToPart", 3, "[.objectName(\"Character\"), .integer, .integer]", ".null", ""),
        [(35, 108)] = new(35, "Character", 108, "setScale", 2, "[.objectName(\"Character\"), .vector]", ".null", ""),
        [(35, 109)] = new(35, "Character", 109, "recalculateBounds", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 110)] = new(35, "Character", 110, "isWithinBoundsVector2", 4, "[.objectName(\"Character\"), .vector, .float, .vector]", ".bool", ""),
        [(35, 111)] = new(35, "Character", 111, "loadTransformationForBone", 2, "[.objectName(\"Character\"), .integer]", ".null", ""),
        [(35, 112)] = new(35, "Character", 112, "applyTextureFilterWithIndex", 2, "[.objectName(\"Character\"), .integerIndex]", ".null", "Applies a preset filter to the textures on the model. The vanilla list of filters are the ones for making pokespot pokemon shiny in the overworld"),
        [(35, 113)] = new(35, "Character", 113, "clearUnknown", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(35, 114)] = new(35, "Character", 114, "clearUnknownStopRotation", 1, "[.objectName(\"Character\")]", ".null", ""),
        [(37, 16)] = new(37, "Pokemon", 16, "playCryForSpeciesWithId", 2, "[.anyType, .pokemon]", ".null", "species id"),
        [(37, 17)] = new(37, "Pokemon", 17, "deleteMove", 2, "[.objectName(\"Pokemon\"), .integerIndex]", ".null", "move slot"),
        [(37, 18)] = new(37, "Pokemon", 18, "copyMoveToIndexFromIndex", 3, "[.objectName(\"Pokemon\"), .integerIndex, .integerIndex]", ".null", "target move slot, original move slot"),
        [(37, 19)] = new(37, "Pokemon", 19, "playCry", 1, "[.objectName(\"Pokemon\")]", ".null", "species id"),
        [(37, 20)] = new(37, "Pokemon", 20, "countMoves", 1, "[.objectName(\"Pokemon\")]", ".integer", ""),
        [(37, 21)] = new(37, "Pokemon", 21, "getPokeballCaughtWith", 1, "[.objectName(\"Pokemon\")]", ".item", ""),
        [(37, 22)] = new(37, "Pokemon", 22, "getNickname", 1, "[.objectName(\"Pokemon\")]", ".string", ""),
        [(37, 24)] = new(37, "Pokemon", 24, "isShadowPokemon", 1, "[.objectName(\"Pokemon\")]", ".bool", ""),
        [(37, 25)] = new(37, "Pokemon", 25, "getMoveAtIndex", 1, "[.objectName(\"Pokemon\"), .integerIndex]", ".move", ""),
        [(37, 26)] = new(37, "Pokemon", 26, "getCurrentHP", 1, "[.objectName(\"Pokemon\")]", ".integer", ""),
        [(37, 27)] = new(37, "Pokemon", 27, "getCurrentPurificationCounter", 1, "[.objectName(\"Pokemon\")]", ".integer", ""),
        [(37, 28)] = new(37, "Pokemon", 28, "getSpecies", 1, "[.objectName(\"Pokemon\")]", ".pokemon", ""),
        [(37, 29)] = new(37, "Pokemon", 29, "isLegendary", 1, "[.objectName(\"Pokemon\")]", ".bool", ""),
        [(37, 30)] = new(37, "Pokemon", 30, "getHappiness", 1, "[.objectName(\"Pokemon\")]", ".integerUnsignedByte", ""),
        [(37, 31)] = new(37, "Pokemon", 31, "getSpeciesNameID", 1, "[.objectName(\"Pokemon\")]", ".msg", ""),
        [(37, 32)] = new(37, "Pokemon", 32, "getHeldItem", 1, "[.objectName(\"Pokemon\")]", ".item", ""),
        [(37, 33)] = new(37, "Pokemon", 33, "getOriginalSIDTID", 1, "[.objectName(\"Pokemon\")]", ".integerUnsigned", ""),
        [(37, 34)] = new(37, "Pokemon", 34, "teachMove", 3, "[.objectName(\"Pokemon\"), .move, .number]", ".integer", ""),
        [(37, 35)] = new(37, "Pokemon", 35, "hasLearnedMove", 2, "[.objectName(\"Pokemon\"), .move]", ".bool", ""),
        [(37, 36)] = new(37, "Pokemon", 36, "canLearnTutorMove", 2, "[.objectName(\"Pokemon\"), .move]", ".bool", ""),
        [(37, 37)] = new(37, "Pokemon", 37, "openTeachNewMoveMenu", 2, "[.objectName(\"Pokemon\"), .move]", ".integerIndex", ""),
        [(37, 38)] = new(37, "Pokemon", 38, "openMoveSelectionMenu", 1, "[.objectName(\"Pokemon\")]", ".integerIndex", ""),
        [(38, 16)] = new(38, "Map", 16, "getCurrentMapID", 1, "[.objectName(\"Map\")]", ".room", ""),
        [(38, 17)] = new(38, "Map", 17, "getCurrentGroupID", 1, "[.objectName(\"Map\")]", ".integer", ""),
        [(38, 18)] = new(38, "Map", 18, "getPreviousMapID", 1, "[.objectName(\"Map\")]", ".room", ""),
        [(38, 19)] = new(38, "Map", 19, "getNextMapID", 1, "[.objectName(\"Map\")]", ".room", ""),
        [(38, 20)] = new(38, "Map", 20, "getNextWarpPointIndex", 1, "[.objectName(\"Map\")]", ".integerIndex", ""),
        [(38, 21)] = new(38, "Map", 21, "setBattleResumeMap", 3, "[.objectName(\"Map\"), .number, .number]", ".integerIndex", ""),
        [(38, 22)] = new(38, "Map", 22, "warpToMap", 3, "[.objectName(\"Map\"), .room, .integerIndex]", ".null", "room id and entry point index"),
        [(38, 23)] = new(38, "Map", 23, "warpToMapWithSoundEffect", 4, "[.objectName(\"Map\"), .room, .integerIndex, .number]", ".null", "room id and entry point index"),
        [(38, 24)] = new(38, "Map", 24, "controlDoor", 4, "[.objectName(\"Map\"), .number, .number, .number]", ".integer", ""),
        [(38, 25)] = new(38, "Map", 25, "controlElevator", 4, "[.objectName(\"Map\"), .number, .number, .number]", ".integer", ""),
        [(38, 26)] = new(38, "Map", 26, "setTreasureVisibility", 3, "[.objectName(\"Map\"), .treasureID, .bool]", ".null", "treasure id, visibility"),
        [(38, 27)] = new(38, "Map", 27, "changeTreasure", 4, "[.objectName(\"Map\"), .number, .number, .number]", ".integer", ""),
        [(38, 28)] = new(38, "Map", 28, "setCharacterVisibility", 3, "[.objectName(\"Map\"), .integerIndex, .bool]", ".bool", "character index, visibility"),
        [(38, 29)] = new(38, "Map", 29, "setCharacterPosition", 5, "[.objectName(\"Map\"), .number, .number, .number, .integerIndex]", ".integer", "x, y, z, character index"),
        [(38, 30)] = new(38, "Map", 30, "setFadeTransitionScript", 3, "[.objectName(\"Map\"), .integerIndex, .bool]", ".bool", "character index, visibility"),
        [(38, 31)] = new(38, "Map", 31, "setBattleResumeMap2", 3, "[.objectName(\"Map\"), .number, .number]", ".null", ""),
        [(38, 32)] = new(38, "Map", 32, "setBattleResumeMap3", 3, "[.objectName(\"Map\"), .number, .number]", ".null", ""),
        [(38, 33)] = new(38, "Map", 33, "clearReturnMap", 1, "[.objectName(\"Map\")]", ".null", ""),
        [(38, 34)] = new(38, "Map", 34, "playMovieWithIndex", 2, "[.objectName(\"Map\"), .integerIndex]", ".integer", ""),
        [(38, 35)] = new(38, "Map", 35, "setCharacterPositionBroken", 2, "nil", ".integer", "Implementation looks buggy so possibly unused"),
        [(38, 36)] = new(38, "Map", 36, "showWorldMap", 1, "[.objectName(\"Map\")]", ".null", ""),
        [(38, 37)] = new(38, "Map", 37, "showTitleScreen", 1, "[.objectName(\"Map\")]", ".null", ""),
        [(38, 38)] = new(38, "Map", 38, "enterMenuMap", 2, "[.objectName(\"Map\"), .room]", ".null", ""),
        [(38, 39)] = new(38, "Map", 39, "showPurifyChamberHolograms", 1, "[.objectName(\"Map\")]", ".null", ""),
        [(38, 40)] = new(38, "Map", 40, "showPurifyChamber", 1, "[.objectName(\"Map\")]", ".null", ""),
        [(38, 41)] = new(38, "Map", 41, "controlElevatorWithCharacter", 5, "[.objectName(\"Map\"), .number, .number, .number, .objectName(\"Character\")]", ".null", ""),
        [(38, 42)] = new(38, "Map", 42, "changePosition", 6, "[.objectName(\"Map\"), .number, .number, .number, .number, .number]", ".null", ""),
        [(38, 43)] = new(38, "Map", 43, "showPurifyChamber2", 1, "[.objectName(\"Map\")]", ".null", ""),
        [(38, 44)] = new(38, "Map", 44, "showBattleBingoMenu", 1, "[.objectName(\"Map\")]", ".null", ""),
        [(38, 45)] = new(38, "Map", 45, "getBattleBingoResult", 1, "[.objectName(\"Map\")]", ".integer", ""),
        [(38, 46)] = new(38, "Map", 46, "getBattleBingoCompletedLines", 1, "[.objectName(\"Map\")]", ".integer", ""),
        [(38, 47)] = new(38, "Map", 47, "getWarpPointsListVector", 1, "[.objectName(\"Map\")]", ".array(.vector)", ""),
        [(38, 48)] = new(38, "Map", 48, "getWarpPointsListFloat", 1, "[.objectName(\"Map\")]", ".array(.float)", ""),
        [(38, 49)] = new(38, "Map", 49, "warpToMapWithTransitions", 4, "[.objectName(\"Map\"), .room, .bool, .scriptFunction, .scriptFunction]", ".null", "room id, unknown, current script function before warp, target room function after warp"),
        [(38, 50)] = new(38, "Map", 50, "playMovieOnTV", 7, "[.objectName(\"Map\"), .number, .number, .number, .number, .number, .number]", ".null", ""),
        [(38, 51)] = new(38, "Map", 51, "showBattleCDMenu", 1, "[.objectName(\"Map\")]", ".null", ""),
        [(38, 52)] = new(38, "Map", 52, "getSelectedBattleCD", 1, "[.objectName(\"Map\")]", ".integerIndex", ""),
        [(38, 53)] = new(38, "Map", 53, "getBattleCDResult", 1, "[.objectName(\"Map\")]", ".integer", ""),
        [(38, 54)] = new(38, "Map", 54, "getBattleBingoLastCardNumber", 1, "[.objectName(\"Map\")]", ".integer", ""),
        [(38, 55)] = new(38, "Map", 55, "getBattleBingoRemainingEP", 1, "[.objectName(\"Map\")]", ".integer", ""),
        [(38, 56)] = new(38, "Map", 56, "getBattleBingoRemainingMasterBalls", 1, "[.objectName(\"Map\")]", ".integer", ""),
        [(38, 57)] = new(38, "Map", 57, "isPurifyChamberReadyForShadowLugiaPurification", 1, "[.objectName(\"Map\")]", ".bool", ""),
        [(38, 58)] = new(38, "Map", 58, "registerLight", 2, "[.objectName(\"Map\"), .number]", ".null", ""),
        [(38, 59)] = new(38, "Map", 59, "registerCamera", 2, "[.objectName(\"Map\"), .number]", ".null", ""),
        [(38, 60)] = new(38, "Map", 60, "beginBattleCD", 1, "[.objectName(\"Map\")]", ".null", ""),
        [(38, 61)] = new(38, "Map", 61, "releaseOverlay", 1, "[.objectName(\"Map\")]", ".null", ""),
        [(38, 62)] = new(38, "Map", 62, "getPurifyChamberTutorialCancelled", 1, "[.objectName(\"Map\")]", ".bool", ""),
        [(38, 63)] = new(38, "Map", 63, "showScooterTransition", 2, "[.objectName(\"Map\"), .number]", ".null", ""),
        [(38, 64)] = new(38, "Map", 64, "isPurifyChamberReadyForShadowLugiaPurification2", 1, "[.objectName(\"Map\")]", ".bool", ""),
        [(38, 65)] = new(38, "Map", 65, "getBattleBingoMode", 1, "[.objectName(\"Map\")]", ".integer", ""),
        [(38, 66)] = new(38, "Map", 66, "countPurifyChamberPokemonReadyToPurify", 1, "[.objectName(\"Map\")]", ".integer", ""),
        [(38, 67)] = new(38, "Map", 67, "setShadowDistanceLimits", 3, "[.objectName(\"Map\"), .number, .number]", ".integer", ""),
        [(39, 16)] = new(39, "Tasks", 16, "executeScriptWithIDSync", 6, "[.objectName(\"Tasks\"), .integer, .integer, .integer, .integer, .integer]", ".null", ""),
        [(39, 17)] = new(39, "Tasks", 17, "executeScriptWithNameSync", 6, "[.objectName(\"Tasks\"), .scriptFunction, .integer, .integer, .integer, .integer]", ".null", ""),
        [(39, 18)] = new(39, "Tasks", 18, "executeScriptWithIDAsync", 6, "[.objectName(\"Tasks\"), .integer, .integer, .integer, .integer, .integer]", ".null", ""),
        [(39, 19)] = new(39, "Tasks", 19, "executeScriptWithNameAsync", 6, "[.objectName(\"Tasks\"), .scriptFunction, .integer, .integer, .integer, .integer]", ".null", ""),
        [(39, 20)] = new(39, "Tasks", 20, "getLastResult", 1, "[.objectName(\"Tasks\")]", ".anyType", ""),
        [(39, 21)] = new(39, "Tasks", 21, "sleep", 2, "[.objectName(\"Tasks\"), .number]", ".null", "(seconds)"),
        [(40, 16)] = new(40, "Menu", 16, "displayMessageSilently", 4, "[.objectName(\"Menu\"), .msg, .bool, .bool]", ".integer", "(msgId, inForeground?, print immediately?)"),
        [(40, 17)] = new(40, "Menu", 17, "displayMessageWithSoundEffect", 5, "[.objectName(\"Menu\"), .msg, .bool, .bool, .integer]", ".integer", "(msgId, inForeground?, print imm.?, pitch)"),
        [(40, 18)] = new(40, "Menu", 18, "awaitMessageClose", 2, "[.objectName(\"Menu\"), .bool]", ".null", "(wait for completion?)"),
        [(40, 19)] = new(40, "Menu", 19, "displayMessageSilently2", 4, "[.objectName(\"Menu\"), .msg, .bool, .bool]", ".integer", "(msgId, inForeground?, print immediately?)"),
        [(40, 20)] = new(40, "Menu", 20, "awaitMessageClose2", 2, "[.objectName(\"Menu\"), .bool]", ".null", "(wait for completion?)"),
        [(40, 21)] = new(40, "Menu", 21, "displayYesNoMenu", 2, "[.objectName(\"Menu\"), .msg]", ".yesNoIndex", "returns 0 = YES, 1 = NO"),
        [(40, 22)] = new(40, "Menu", 22, "displayYesNoMenuWithOptions", 5, "[.objectName(\"Menu\"), .msg, .number, .number, .number]", ".yesNoIndex", "msg id, x, y, starting selection,, returns 0 = YES, 1 = NO"),
        [(40, 23)] = new(40, "Menu", 23, "openColosseumEntryMenu", 2, "[.objectName(\"Menu\"), .number]", ".null", ""),
        [(40, 24)] = new(40, "Menu", 24, "openMenuWithId", 3, "[.objectName(\"Menu\"), .number, .bool]", ".integer", ""),
        [(40, 25)] = new(40, "Menu", 25, "awaitMenuClose", 2, "[.objectName(\"Menu\"), .bool]", ".null", "(wait for completion?)"),
        [(40, 26)] = new(40, "Menu", 26, "getCursorPositionForMenu", 2, "[.objectName(\"Menu\"), .number]", ".integer", ""),
        [(40, 27)] = new(40, "Menu", 27, "setCursorPositionForMenu", 3, "[.objectName(\"Menu\"), .number, .number]", ".null", ""),
        [(40, 28)] = new(40, "Menu", 28, "setMessageVariable", 3, "[.objectName(\"Menu\"), .msgVar, .variableType]", ".null", ""),
        [(40, 29)] = new(40, "Menu", 29, "displayCustomMenu", 6, "[.objectName(\"Menu\"), .array(.msg), .integer, .integer, .integer, .integerIndex]", ".integerIndex", "(msgIDs, no. elems, x, y, selection)"),
        [(40, 32)] = new(40, "Menu", 32, "displayPartyPokemonMenu", 1, "[.objectName(\"Menu\")]", ".integerIndex", ""),
        [(40, 33)] = new(40, "Menu", 33, "displayPartyPokemonMenu2", 1, "[.objectName(\"Menu\")]", ".integerIndex", ""),
        [(40, 34)] = new(40, "Menu", 34, "displayPokemonSummary", 2, "[.objectName(\"Menu\"), .integerIndex]", ".null", ""),
        [(40, 35)] = new(40, "Menu", 35, "displayMoveMenuForPokemon", 2, "[.objectName(\"Menu\"), .integerIndex]", ".integerIndex", ""),
        [(40, 36)] = new(40, "Menu", 36, "displayNameEntryMenu", 3, "[.objectName(\"Menu\"), .integer, .integer]", ".null", "(forWhom, mode)"),
        [(40, 37)] = new(40, "Menu", 37, "commonScriptDisplayNameEntryMenu", 3, "[.objectName(\"Menu\"), .integer, .integer]", ".null", "only use in common.rel's script"),
        [(40, 39)] = new(40, "Menu", 39, "displayShopMenu", 2, "[.objectName(\"Menu\"), .integer]", ".null", "(mart id)"),
        [(40, 41)] = new(40, "Menu", 41, "displayPDAMenu", 1, "[.objectName(\"Menu\")]", ".null", ""),
        [(40, 42)] = new(40, "Menu", 42, "openTradingMenu", 1, "[.objectName(\"Menu\")]", ".bool", ""),
        [(40, 50)] = new(40, "Menu", 50, "openItemMenu", 1, "[.objectName(\"Menu\")]", ".null", ""),
        [(40, 56)] = new(40, "Menu", 56, "openNumberInputMenu", 2, "[.objectName(\"Menu\"), .number]", ".integer", ""),
        [(40, 57)] = new(40, "Menu", 57, "openTutorialMenu", 1, "[.objectName(\"Menu\")]", ".null", ""),
        [(40, 58)] = new(40, "Menu", 58, "openEeveeEvolutionsMenu", 1, "[.objectName(\"Menu\")]", ".null", ""),
        [(40, 59)] = new(40, "Menu", 59, "displayMenuWithOptions", 8, "[.objectName(\"Menu\"), .number, .array(.msg), .number, .number, .number, .number, .number]", ".integerIndex", "(msgIDs, no. elems, x, y, selection)"),
        [(40, 60)] = new(40, "Menu", 60, "showWorldMapLocation", 2, "[.objectName(\"Menu\"), .integer]", ".null", ""),
        [(40, 61)] = new(40, "Menu", 61, "showMirorRadarIcon", 1, "[.objectName(\"Menu\")]", ".null", ""),
        [(40, 62)] = new(40, "Menu", 62, "hideMirorRadarIcon", 1, "[.objectName(\"Menu\")]", ".null", ""),
        [(40, 63)] = new(40, "Menu", 63, "showBonslyPhoto", 1, "[.objectName(\"Menu\")]", ".null", ""),
        [(40, 64)] = new(40, "Menu", 64, "openMoveRelearnerMenuForPartyMember", 2, "[.objectName(\"Menu\"), .integerIndex]", ".move", ""),
        [(40, 65)] = new(40, "Menu", 65, "openTutorMovesMenu", 1, "[.objectName(\"Menu\")]", ".move", ""),
        [(40, 66)] = new(40, "Menu", 66, "setTutorMoveLearnedFlag", 2, "[.objectName(\"Menu\"), .move]", ".null", ""),
        [(40, 67)] = new(40, "Menu", 67, "showMoneyWindow", 3, "[.objectName(\"Menu\"), .integer, .integer]", ".null", "(x, y)"),
        [(40, 68)] = new(40, "Menu", 68, "hideMoneyWindow", 1, "[.objectName(\"Menu\")]", ".null", ""),
        [(40, 69)] = new(40, "Menu", 69, "isMoveTutorAvailable", 1, "[.objectName(\"Menu\")]", ".bool", ""),
        [(40, 70)] = new(40, "Menu", 70, "showCouponsWindow", 3, "[.objectName(\"Menu\"), .integer, .integer]", ".null", "(x, y)"),
        [(40, 71)] = new(40, "Menu", 71, "hideCouponsWindow", 1, "[.objectName(\"Menu\")]", ".null", ""),
        [(40, 72)] = new(40, "Menu", 72, "showOrreColosseumMenu", 2, "[.objectName(\"Menu\"), .battleID]", ".null", ""),
        [(40, 74)] = new(40, "Menu", 74, "getOrreColosseumResult", 1, "[.objectName(\"Menu\")]", ".battleResult", "1 = lose, 2 = win, 3 = tie"),
        [(40, 75)] = new(40, "Menu", 75, "addPDAFunctionality", 2, "[.objectName(\"Menu\"), .number]", ".null", ""),
        [(40, 76)] = new(40, "Menu", 76, "bagMenuAddItemScript", 3, "[.objectName(\"Menu\"), .number, .number]", ".null", ""),
        [(40, 77)] = new(40, "Menu", 77, "beginMewMoveTutorQuestions", 1, "[.objectName(\"Menu\")]", ".integer", ""),
        [(40, 78)] = new(40, "Menu", 78, "getGeneratedMewTutorMoveWithIndex", 2, "[.objectName(\"Menu\"), .integerIndex]", ".move", "After the questions have been asked this function is used to retrieve the moveset"),
        [(40, 79)] = new(40, "Menu", 79, "openPartyMenuToLearnMove", 2, "[.objectName(\"Menu\"), .move]", ".integerIndex", "shows which pokemon can learn the move"),
        [(40, 763)] = new(40, "Menu", 763, "showBonslyPhoto2", 1, "[.objectName(\"Menu\")]", ".null", ""),
        [(41, 16)] = new(41, "Transition", 16, "begin", 3, "[.objectName(\"Transition\"), .transitionID, .number]", ".null", "(duration in seconds)"),
        [(41, 17)] = new(41, "Transition", 17, "await", 2, "[.objectName(\"Transition\"), .bool]", ".null", "(wait for completion?)"),
        [(42, 16)] = new(42, "Battle", 16, "startScriptedBattle", 4, "[.objectName(\"Battle\"), .battleID, .bool, .bool]", ".null", "(battle id, unknown, don't black out?)"),
        [(42, 17)] = new(42, "Battle", 17, "startOpenBattle", 2, "[.objectName(\"Battle\"), .battleID]", ".null", "returns battle result rather than automatically handling black out"),
        [(42, 18)] = new(42, "Battle", 18, "getBattleResult", 1, "[.objectName(\"Battle\")]", ".battleResult", "1 = lose, 2 = win, 3 = tie"),
        [(42, 19)] = new(42, "Battle", 19, "playBGMForCurrentBattle", 2, "[.objectName(\"Battle\"), .bool]", ".null", ""),
        [(42, 20)] = new(42, "Battle", 20, "playEnvironmentSoundsForCurrentBattle", 2, "[.objectName(\"Battle\"), .bool]", ".null", ""),
        [(42, 21)] = new(42, "Battle", 21, "startBattleDependentOnShadowPokemonCaught", 3, "[.objectName(\"Battle\"), .shadowID, .battleID, .battleID]", ".null", ""),
        [(42, 22)] = new(42, "Battle", 22, "getCurrentBattleString", 1, "[.objectName(\"Battle\")]", ".string", ""),
        [(42, 23)] = new(42, "Battle", 23, "setNextBattlefield", 2, "[.objectName(\"Battle\"), .battlefield]", ".null", "overrides next battle"),
        [(42, 24)] = new(42, "Battle", 24, "getNextBattlefield", 1, "[.objectName(\"Battle\")]", ".battlefield", ""),
        [(42, 25)] = new(42, "Battle", 25, "getNextPostBattleText", 3, "[.objectName(\"Battle\"), .battleResult]", ".msg", ""),
        [(42, 26)] = new(42, "Battle", 26, "setNextPostBattleText", 3, "[.objectName(\"Battle\"), .battleResult, .msg]", ".null", "overrides next battle"),
        [(42, 27)] = new(42, "Battle", 27, "getNextAddMode", 1, "[.objectName(\"Battle\")]", ".integer", ""),
        [(42, 28)] = new(42, "Battle", 28, "getNextAddPlace", 1, "[.objectName(\"Battle\")]", ".integer", ""),
        [(42, 29)] = new(42, "Battle", 29, "getNextAddId", 1, "[.objectName(\"Battle\")]", ".integer", ""),
        [(42, 30)] = new(42, "Battle", 30, "setNextAddSettings", 4, "[.objectName(\"Battle\"), .number, .number, .number]", ".null", "mode, place, id"),
        [(42, 31)] = new(42, "Battle", 31, "getNextSwitchMode", 1, "[.objectName(\"Battle\")]", ".integer", ""),
        [(42, 32)] = new(42, "Battle", 32, "getNextSwitchDeckDisabled", 1, "[.objectName(\"Battle\")]", ".integer", ""),
        [(42, 33)] = new(42, "Battle", 33, "setNextSwitchSettings", 3, "[.objectName(\"Battle\"), .number, .number]", ".null", "mode, deck disabled?"),
        [(42, 34)] = new(42, "Battle", 34, "getNextSwitchDeckDisabled2", 1, "[.objectName(\"Battle\")]", ".integer", ""),
        [(42, 35)] = new(42, "Battle", 35, "setNextBattleType", 2, "[.objectName(\"Battle\"), .number]", ".null", ""),
        [(42, 36)] = new(42, "Battle", 36, "getNextBattleEraseFlag", 1, "[.objectName(\"Battle\")]", ".integer", ""),
        [(42, 37)] = new(42, "Battle", 37, "setNextBattleEraseFlag", 2, "[.objectName(\"Battle\"), .number]", ".null", ""),
        [(42, 38)] = new(42, "Battle", 38, "getNextTrainerType", 1, "[.objectName(\"Battle\")]", ".integer", ""),
        [(42, 39)] = new(42, "Battle", 39, "setNextTrainerType", 2, "[.objectName(\"Battle\"), .number]", ".null", ""),
        [(42, 40)] = new(42, "Battle", 40, "recoverAfterTeamWipeOut", 1, "[.objectName(\"Battle\")]", ".null", ""),
        [(42, 41)] = new(42, "Battle", 41, "getNextColosseumRound", 1, "[.objectName(\"Battle\")]", ".integer", ""),
        [(42, 42)] = new(42, "Battle", 42, "setNextColosseumRound", 2, "[.objectName(\"Battle\"), .number]", ".null", ""),
        [(43, 16)] = new(43, "Player", 16, "initializePlayerAndFollower", 1, "[.objectName(\"Player\")]", ".integer", ""),
        [(43, 17)] = new(43, "Player", 17, "processEvents", 1, "[.objectName(\"Player\")]", ".integer", "only use in hero_main"),
        [(43, 18)] = new(43, "Player", 18, "lockMovement", 1, "[.objectName(\"Player\")]", ".null", ""),
        [(43, 19)] = new(43, "Player", 19, "freeMovement", 1, "[.objectName(\"Player\")]", ".null", ""),
        [(43, 20)] = new(43, "Player", 20, "triggerScript", 6, "[.objectName(\"Player\"), .scriptFunction, .anyType, .anyType, .anyType, .anyType]", ".null", "Used to trigger a script with the given parameters"),
        [(43, 21)] = new(43, "Player", 21, "setJoviFollowerStatus", 2, "[.objectName(\"Player\"), .bool]", ".null", ""),
        [(43, 22)] = new(43, "Player", 22, "setFollowerShouldHeadTrackPlayer", 3, "[.objectName(\"Player\"), .partyMember, .bool]", ".integer", "npc party member index, enable/disable"),
        [(43, 23)] = new(43, "Player", 23, "checkFollower", 1, "[.objectName(\"Player\")]", ".integer", "doesn't seem to return a meaningful value. Possible Colosseum leftover"),
        [(43, 24)] = new(43, "Player", 24, "controlElevator", 5, "[.objectName(\"Player\"), .number, .number, .number, .number]", ".integer", ""),
        [(43, 25)] = new(43, "Player", 25, "awaitFollowerMovement", 1, "[.objectName(\"Player\")]", ".integer", ""),
        [(43, 26)] = new(43, "Player", 26, "receiveItem", 3, "[.objectName(\"Player\"), .item, .integerQuantity]", ".bool", "use negative quantity to take item"),
        [(43, 27)] = new(43, "Player", 27, "receiveItemSilently", 3, "[.objectName(\"Player\"), .item, .integerQuantity]", ".bool", "use negative quantity to take item"),
        [(43, 28)] = new(43, "Player", 28, "hasItemInBag", 2, "[.objectName(\"Player\"), .item]", ".bool", ""),
        [(43, 29)] = new(43, "Player", 29, "receiveMoney", 2, "[.objectName(\"Player\"), .integerMoney]", ".integer", "use negative quantity to take money"),
        [(43, 30)] = new(43, "Player", 30, "getMoneyTotal", 1, "[.objectName(\"Player\")]", ".integerMoney", ""),
        [(43, 31)] = new(43, "Player", 31, "getPrizeMoneyBuffer", 1, "[.objectName(\"Player\")]", ".integerMoney", "stored from colosseum battles"),
        [(43, 32)] = new(43, "Player", 32, "setPrizeMoneyBuffer", 2, "[.objectName(\"Player\"), .integerMoney]", ".null", "stored from colosseum battles"),
        [(43, 33)] = new(43, "Player", 33, "addToPrizeMoneyBuffer", 2, "[.objectName(\"Player\"), .integerMoney]", ".null", "stored from colosseum battles"),
        [(43, 34)] = new(43, "Player", 34, "countPartyPokemon", 1, "[.objectName(\"Player\")]", ".integer", ""),
        [(43, 35)] = new(43, "Player", 35, "countShadowPartyPokemon", 1, "[.objectName(\"Player\")]", ".integer", ""),
        [(43, 36)] = new(43, "Player", 36, "getPartyPokemonName", 2, "[.objectName(\"Player\"), .integerIndex]", ".string", ""),
        [(43, 37)] = new(43, "Player", 37, "receiveGiftPokemon", 2, "[.objectName(\"Player\"), .giftPokemon]", ".integer", ""),
        [(43, 38)] = new(43, "Player", 38, "countPurifiablePartyPokemon", 1, "[.objectName(\"Player\")]", ".integer", ""),
        [(43, 39)] = new(43, "Player", 39, "healParty", 1, "[.objectName(\"Player\"), .bool]", ".null", ""),
        [(43, 40)] = new(43, "Player", 40, "returnToColosseumBattleMenu", 2, "[.objectName(\"Player\"), .number]", ".bool", "the parameter is unused"),
        [(43, 41)] = new(43, "Player", 41, "countNonFaintedPartyPokemon", 1, "[.objectName(\"Player\")]", ".integer", ""),
        [(43, 42)] = new(43, "Player", 42, "getFirstEmptyPartyPokemonIndex", 1, "[.objectName(\"Player\")]", ".integerIndex", "returns -1 if full"),
        [(43, 43)] = new(43, "Player", 43, "countPartyPokemon", 1, "[.objectName(\"Player\")]", ".integer", ""),
        [(43, 44)] = new(43, "Player", 44, "getPartyPokemonAtIndex", 2, "[.objectName(\"Player\"), .integerIndex]", ".objectName(\"Pokemon\")", ""),
        [(43, 45)] = new(43, "Player", 45, "checkIfIsOTForPokemon", 2, "[.objectName(\"Player\"), .objectName(\"Pokemon\")]", ".bool", ""),
        [(43, 46)] = new(43, "Player", 46, "changeFollower", 2, "[.objectName(\"Player\"), .partyMember]", ".null", ""),
        [(43, 47)] = new(43, "Player", 47, "getFollower", 1, "[.objectName(\"Player\")]", ".partyMember", ""),
        [(43, 48)] = new(43, "Player", 48, "setCharacterAsFollower", 3, "[.objectName(\"Player\"), .objectName(\"Character\"), .partyMember]", ".null", ""),
        [(43, 49)] = new(43, "Player", 49, "countCaughtShadowPokemon", 1, "[.objectName(\"Player\")]", ".integer", ""),
        [(43, 50)] = new(43, "Player", 50, "graduallyStopMoving", 1, "[.objectName(\"Player\")]", ".null", ""),
        [(43, 51)] = new(43, "Player", 51, "hasPokemonReadyForPurification", 1, "[.objectName(\"Player\")]", ".bool", ""),
        [(43, 52)] = new(43, "Player", 52, "isPCFull", 1, "[.objectName(\"Player\")]", ".bool", ""),
        [(43, 53)] = new(43, "Player", 53, "countLegendaryPartyPokemon", 1, "[.objectName(\"Player\")]", ".integer", ""),
        [(43, 54)] = new(43, "Player", 54, "setFollower", 3, "[.objectName(\"Player\"), .partyMember, .integer]", ".null", "set to 0 to remove"),
        [(43, 55)] = new(43, "Player", 55, "storePartyPokemon", 1, "[.objectName(\"Player\")]", ".null", ""),
        [(43, 56)] = new(43, "Player", 56, "checkStoredPartyPokemon", 1, "[.objectName(\"Player\")]", ".integer", ""),
        [(43, 57)] = new(43, "Player", 57, "healPartyWithJingle", 1, "[.objectName(\"Player\")]", ".null", ""),
        [(43, 58)] = new(43, "Player", 58, "healPartyAtPokeCenter", 4, "[.objectName(\"Player\"), .number, .array(.objectName(\"Pokemon\")), .array(.objectName(\"Pokemon\"))]", ".null", ""),
        [(43, 59)] = new(43, "Player", 59, "countPurfiedPokemon", 1, "[.objectName(\"Player\")]", ".integer", ""),
        [(43, 60)] = new(43, "Player", 60, "awardMtBattleRibbons", 1, "[.objectName(\"Player\")]", ".null", ""),
        [(43, 61)] = new(43, "Player", 61, "getCouponTotal", 1, "[.objectName(\"Player\")]", ".integerCoupons", ""),
        [(43, 62)] = new(43, "Player", 62, "setCouponTotal", 2, "[.objectName(\"Player\"), .integerCoupons]", ".null", ""),
        [(43, 63)] = new(43, "Player", 63, "receiveCoupons", 2, "[.objectName(\"Player\"), .integerCoupons]", ".null", "use negative quantity to take coupons"),
        [(43, 64)] = new(43, "Player", 64, "countAllShadowPokemon", 1, "[.objectName(\"Player\")]", ".integer", "total number of shadow pokemon in game"),
        [(43, 65)] = new(43, "Player", 65, "setStyle", 3, "[.objectName(\"Player\"), .integer, .bool]", ".null", ""),
        [(43, 66)] = new(43, "Player", 66, "setSmoothWarp", 2, "[.objectName(\"Player\"), .bool]", ".null", ""),
        [(43, 67)] = new(43, "Player", 67, "obtainItem", 5, "[.objectName(\"Player\"), .number, .item, .integerQuantity, .bool]", ".null", ""),
        [(43, 68)] = new(43, "Player", 68, "hasSpeciesInPC", 2, "[.objectName(\"Player\"), .pokemon]", ".bool", ""),
        [(43, 69)] = new(43, "Player", 69, "releasePartyPokemon", 2, "[.objectName(\"Player\"), .integerIndex]", ".bool", "returns true if worked"),
        [(44, 16)] = new(44, "Light", 16, "setVisibility", 3, "[.objectName(\"Light\"), .number, .bool]", ".null", "id, visibility"),
        [(44, 17)] = new(44, "Light", 17, "setAnimation", 5, "[.objectName(\"Light\"), .number, .number, .number, .number]", ".null", ""),
        [(44, 18)] = new(44, "Light", 18, "stopAnimation", 2, "[.objectName(\"Light\"), .number]", ".null", ""),
        [(44, 19)] = new(44, "Light", 19, "awaitAnimation", 2, "[.objectName(\"Light\"), .number, .bool]", ".integer", "id, wait for completion?"),
        [(44, 20)] = new(44, "Light", 20, "setType", 3, "[.objectName(\"Light\"), .number, .number]", ".null", ""),
        [(44, 21)] = new(44, "Light", 21, "setPosition", 3, "[.objectName(\"Light\"), .number, .vector]", ".null", ""),
        [(44, 22)] = new(44, "Light", 22, "setColor", 6, "[.objectName(\"Light\"), .number, .number, .number, .number, .number]", ".null", "id, r,g,b,a"),
        [(44, 23)] = new(44, "Light", 23, "getPostion", 2, "[.objectName(\"Light\"), .number]", ".vector", ""),
        [(45, 16)] = new(45, "Model", 16, "open", 2, "[.objectName(\"Model\"), .number]", ".integer", ""),
        [(45, 17)] = new(45, "Model", 17, "close", 2, "[.objectName(\"Model\"), .null]", ".integer", ""),
        [(45, 18)] = new(45, "Model", 18, "setVisibility", 3, "[.objectName(\"Model\"), .number, .bool]", ".null", "id, visibility"),
        [(45, 19)] = new(45, "Model", 19, "setAnimation", 5, "[.objectName(\"Model\"), .datsIdentifier, .number, .number, .number]", ".null", ""),
        [(45, 20)] = new(45, "Model", 20, "stopAnimation", 2, "[.objectName(\"Model\"), .number]", ".null", ""),
        [(45, 21)] = new(45, "Model", 21, "awaitAnimation", 3, "[.objectName(\"Model\"), .datsIdentifier, .bool]", ".null", "(wait for completion?)"),
        [(45, 22)] = new(45, "Model", 22, "attach", 4, "[.objectName(\"Model\"), .number, .number, .number]", ".integer", ""),
        [(45, 23)] = new(45, "Model", 23, "detach", 2, "[.objectName(\"Model\"), .number]", ".integer", ""),
        [(45, 24)] = new(45, "Model", 24, "setParticleEffect", 4, "[.objectName(\"Model\"), .number, .number, .number]", ".null", ""),
        [(45, 25)] = new(45, "Model", 25, "removeParticleEffect", 3, "[.objectName(\"Model\"), .number, .number]", ".null", ""),
        [(45, 26)] = new(45, "Model", 26, "getTransformationForBone", 3, "[.objectName(\"Model\"), .number, .number]", ".vector", ""),
        [(45, 27)] = new(45, "Model", 27, "addPosition", 3, "[.objectName(\"Model\"), .number, .vector]", ".null", ""),
        [(45, 28)] = new(45, "Model", 28, "iterateList", 2, "[.objectName(\"Model\"), .number]", ".null", ""),
        [(45, 29)] = new(45, "Model", 29, "setAnimationSpeed", 6, "[.objectName(\"Model\"), .number, .number, .number, .float, .number]", ".null", ""),
        [(45, 30)] = new(45, "Model", 30, "setBoundsCheckingForCharacterRId", 3, "[.objectName(\"Model\"), .number, .bool]", ".null", "resource id, bounds enabled?"),
        [(45, 31)] = new(45, "Model", 31, "setAnimationEnded", 4, "[.objectName(\"Model\"), .number, .number, .number]", ".integer", ""),
        [(45, 32)] = new(45, "Model", 32, "attachParticleToPart", 4, "[.objectName(\"Model\"), .number, .number, .number]", ".null", ""),
        [(45, 33)] = new(45, "Model", 33, "setFractionalFramesFlag", 3, "[.objectName(\"Model\"), .number, .bool]", ".null", ""),
        [(45, 34)] = new(45, "Model", 34, "characterRIdRecalculateBounds", 2, "[.objectName(\"Model\"), .number]", ".null", "resource id"),
        [(45, 35)] = new(45, "Model", 35, "characterRIdAnimateFromRootBone", 2, "[.objectName(\"Model\"), .number]", ".null", "resource id"),
        [(46, 16)] = new(46, "Collision", 16, "setEnabled", 3, "[.objectName(\"Collision\"), .number, .bool]", ".null", "id, is enabled?"),
        [(46, 17)] = new(46, "Collision", 17, "getEventCollision", 1, "[.objectName(\"Collision\")]", ".null", "Doesn't return a value so possibly unused"),
        [(46, 18)] = new(46, "Collision", 18, "setEventCollision", 2, "[.objectName(\"Collision\"), .bool]", ".null", ""),
        [(47, 16)] = new(47, "Sound", 16, "playBGM", 4, "[.objectName(\"Sound\"), .sfxID, .number, .number]", ".integer", "(id, unk, volume)"),
        [(47, 17)] = new(47, "Sound", 17, "playEnvironmentSound", 4, "[.objectName(\"Sound\"), .sfxID, .number, .number]", ".integer", "(id, unk, volume)"),
        [(47, 18)] = new(47, "Sound", 18, "stopBGM", 3, "[.objectName(\"Sound\"), .sfxID, .number]", ".integer", "(id, unk)"),
        [(47, 19)] = new(47, "Sound", 19, "stopEnvironmentSound", 2, "[.objectName(\"Sound\"), .sfxID]", ".integer", "(id, unk)"),
        [(47, 20)] = new(47, "Sound", 20, "createEmitter", 5, "[.objectName(\"Sound\"), .number, .float, .float, .float]", ".integer", ""),
        [(47, 21)] = new(47, "Sound", 21, "createListener", 1, "[.objectName(\"Sound\")]", ".integer", ""),
        [(47, 22)] = new(47, "Sound", 22, "setVolume", 3, "[.objectName(\"Sound\"), .number, .number]", ".integer", ""),
        [(47, 23)] = new(47, "Sound", 23, "playEffect", 4, "[.objectName(\"Sound\"), .number, .number, .number]", ".integer", ""),
        [(47, 24)] = new(47, "Sound", 24, "setVolumeId", 4, "[.objectName(\"Sound\"), .number, .number, .number]", ".integer", ""),
        [(47, 25)] = new(47, "Sound", 25, "transitionToBGM", 5, "[.objectName(\"Sound\"), .sfxID, .number, .number, .number]", ".integer", "id, unk, unk, volume"),
        [(47, 26)] = new(47, "Sound", 26, "transitionToEnvironmentSound", 5, "[.objectName(\"Sound\"), .sfxID, .number, .number, .number]", ".integer", "id, unk, unk, volume"),
        [(47, 27)] = new(47, "Sound", 27, "getBGM", 1, "[.objectName(\"Sound\")]", ".sfxID", ""),
        [(47, 28)] = new(47, "Sound", 28, "characterDialogBGMMask", 2, "[.objectName(\"Sound\"), .bool]", ".null", ""),
        [(47, 29)] = new(47, "Sound", 29, "setCharacterDialogBGMFadeSpeed", 3, "[.objectName(\"Sound\"), .float, .float]", ".null", ""),
        [(47, 30)] = new(47, "Sound", 30, "setCharacterDialogBGMVolumeRate", 3, "[.objectName(\"Sound\"), .float]", ".null", ""),
        [(47, 31)] = new(47, "Sound", 31, "await", 2, "[.objectName(\"Sound\"), .integer]", ".null", ""),
        [(47, 32)] = new(47, "Sound", 32, "playEffect2", 4, "[.objectName(\"Sound\"), .integer, .integer, .integer]", ".integer", ""),
        [(47, 33)] = new(47, "Sound", 33, "createSoundEffectThread", 5, "[.objectName(\"Tasks\"), .integer, .integer, .integer, .integer]", ".null", ""),
        [(48, 16)] = new(48, "Controller", 16, "isPressingAnyButtonOrStickInput", 1, "[.objectName(\"Controller\")]", ".bool", ""),
        [(48, 17)] = new(48, "Controller", 17, "isPressingAnyStickInput", 1, "[.objectName(\"Controller\")]", ".bool", ""),
        [(48, 18)] = new(48, "Controller", 18, "isPressingAnyButton", 1, "[.objectName(\"Controller\")]", ".bool", ""),
        [(48, 19)] = new(48, "Controller", 19, "createRumbleThread", 5, "[.objectName(\"Controller\"), .integer, .integer, .integer, .integer]", ".null", ""),
        [(48, 20)] = new(48, "Controller", 20, "getPressedButtons", 1, "[.objectName(\"Controller\")]", ".buttonInput", ""),
        [(49, 16)] = new(49, "PDA", 16, "receiveMailWithID", 1, "[.objectName(\"PDA\"), .integer]", ".null", ""),
        [(49, 17)] = new(49, "PDA", 17, "setMemoFlag", 1, "[.objectName(\"PDA\")]", ".null", ""),
        [(49, 18)] = new(49, "PDA", 18, "openMailMenu", 2, "[.objectName(\"PDA\"), .integer]", ".null", ""),
        [(49, 19)] = new(49, "PDA", 19, "readMailWithID", 2, "[.objectName(\"PDA\"), .integer]", ".null", ""),
        [(49, 20)] = new(49, "PDA", 20, "receiveMailWithIDAndOpen", 2, "[.objectName(\"PDA\"), .integer]", ".null", ""),
        [(50, 16)] = new(50, "Direction", 16, "beginEvolution", 1, "[.objectName(\"Direction\")]", ".null", ""),
        [(50, 17)] = new(50, "Direction", 17, "setupPurificationParameters", 4, "[.objectName(\"Direction\"), .integer, .integer, .bool]", ".null", ""),
        [(50, 18)] = new(50, "Direction", 18, "beginPurification", 1, "[.objectName(\"Direction\")]", ".null", ""),
        [(50, 19)] = new(50, "Direction", 19, "showRelicStoneParticleEffect", 1, "[.objectName(\"Direction\")]", ".null", ""),
        [(50, 20)] = new(50, "Direction", 20, "useCologne", 3, "[.objectName(\"Direction\"), .integer, .integer]", ".integer", ""),
        [(50, 21)] = new(50, "Direction", 21, "getMirorBLocation", 1, "[.objectName(\"Direction\")]", ".integer", ""),
        [(50, 22)] = new(50, "Direction", 22, "clearMirorBAppearance", 1, "[.objectName(\"Direction\")]", ".null", ""),
        [(51, 17)] = new(51, "TV", 17, "controlTVEvent", 1, "[.objectName(\"TV\"), .integer]", ".integer", ""),
        [(52, 17)] = new(52, "Daycare", 17, "getLevelsGained", 1, "[.objectName(\"Daycare\")]", ".integer", ""),
        [(52, 18)] = new(52, "Daycare", 18, "getHundredsOfShadowCounterLost", 1, "[.objectName(\"Daycare\")]", ".integer", "can't deposit shadow pokemon in xd"),
        [(52, 19)] = new(52, "Daycare", 19, "depositPokemon", 2, "[.objectName(\"Daycare\"), .integerIndex]", ".null", ""),
        [(52, 20)] = new(52, "Daycare", 20, "withdrawPokemon", 2, "[.objectName(\"Daycare\"), .integerIndex]", ".null", ""),
        [(52, 22)] = new(52, "Daycare", 22, "calculateFee", 2, "[.objectName(\"Daycare\"), .integer]", ".integerMoney", ""),
        [(52, 23)] = new(52, "Daycare", 23, "checkIfHasPokemonDeposited", 1, "[.objectName(\"Daycare\")]", ".bool", ""),
        [(52, 24)] = new(52, "Daycare", 24, "getDepositedPokemonData", 1, "[.objectName(\"Daycare\")]", ".objectName(\"Pokemon\")", ""),
        [(54, 16)] = new(54, "Thread", 16, "createThread", 2, "[.objectName(\"TaskManager\"), .integer]", ".integer", "possibly broken"),
        [(54, 17)] = new(54, "Thread", 17, "zero", 1, "[.objectName(\"TaskManager\")]", ".integer", "returns 0"),
        [(54, 18)] = new(54, "Thread", 18, "getTaskCounter", 1, "[.objectName(\"TaskManager\")]", ".integer", ""),
        [(54, 19)] = new(54, "Thread", 19, "deleteThread", 2, "[.objectName(\"TaskManager\"), .integer]", ".null", ""),
        [(58, 16)] = new(58, "Move", 16, "initializeSequence", 1, "[.anyType]", ".objectName(\"Move\")", ""),
        [(58, 17)] = new(58, "Move", 17, "beginAnimation", 5, "[.objectName(\"Move\"), .integer, .integer, .integer, .bool]", ".null", "(id, seconds, unk, unk)"),
        [(58, 18)] = new(58, "Move", 18, "setPosition", 2, "[.objectName(\"Move\"), .vector]", ".null", ""),
        [(58, 19)] = new(58, "Move", 19, "setRotation", 2, "[.objectName(\"Move\"), .vector]", ".null", ""),
        [(58, 20)] = new(58, "Move", 20, "setScale", 2, "[.objectName(\"Move\"), .vector]", ".null", ""),
        [(58, 21)] = new(58, "Move", 21, "await", 2, "[.objectName(\"Move\"), .bool]", ".null", "wait for completion?"),
        [(58, 22)] = new(58, "Move", 22, "deinitializeSequence", 1, "[.objectName(\"Move\")]", ".null", ""),
        [(59, 16)] = new(59, "ShadowPokemon", 16, "isShadowPokemonPurified", 2, "[.objectName(\"ShadowPokemon\"), .shadowID]", ".bool", ""),
        [(59, 17)] = new(59, "ShadowPokemon", 17, "isShadowPokemonCaught", 2, "[.objectName(\"ShadowPokemon\"), .shadowID]", ".bool", ""),
        [(59, 18)] = new(59, "ShadowPokemon", 18, "setShadowPokemonStatus", 3, "[.objectName(\"ShadowPokemon\"), .shadowID, .shadowStatus]", ".null", ""),
        [(59, 19)] = new(59, "ShadowPokemon", 19, "getShadowPokemonSpecies", 2, "[.objectName(\"ShadowPokemon\"), .shadowID]", ".pokemon", ""),
        [(59, 20)] = new(59, "ShadowPokemon", 20, "getShadowPokemonStatus", 2, "[.objectName(\"ShadowPokemon\"), .shadowID]", ".shadowStatus", ""),
        [(59, 21)] = new(59, "ShadowPokemon", 21, "setShadowPokemonEncountered", 1, "[.objectName(\"ShadowPokemon\")]", ".null", ""),
        [(59, 22)] = new(59, "ShadowPokemon", 22, "setShadowPokemonPCLocation", 4, "[.objectName(\"ShadowPokemon\"), .shadowID, .PCBox, .integerIndex]", ".null", "(box number, position)"),
        [(60, 16)] = new(60, "Pokespot", 16, "openPokesnackInputMenu", 2, "[.objectName(\"Pokespot\"), .pokespot]", ".integer", "(pokespot id)"),
        [(60, 17)] = new(60, "Pokespot", 17, "getCurrentWildPokemon", 2, "[.objectName(\"Pokespot\"), .pokespot]", ".pokemon", "(pokespot id)"),
        [(60, 18)] = new(60, "Pokespot", 18, "setSnacksTotal", 3, "[.objectName(\"Pokespot\"), .pokespot, .integerQuantity]", ".null", "(pokespot id, total)"),
        [(60, 19)] = new(60, "Pokespot", 19, "getSnacksTotal", 3, "[.objectName(\"Pokespot\"), .pokespot]", ".integerQuantity", "(pokespot id, total)"),
        [(60, 20)] = new(60, "Pokespot", 20, "isEncounterShiny", 2, "[.objectName(\"Pokespot\"), .pokespot]", ".bool", "(pokespot id)"),
    });

    private static readonly IReadOnlyDictionary<string, int> ClassIdsByName = new ReadOnlyDictionary<string, int>(
        ClassNames.ToDictionary(pair => pair.Value, pair => pair.Key, StringComparer.OrdinalIgnoreCase));

    private static readonly IReadOnlyDictionary<(int ClassId, string FunctionName), GameCubeScriptFunctionInfo> FunctionsByName = new ReadOnlyDictionary<(int ClassId, string FunctionName), GameCubeScriptFunctionInfo>(
        FunctionsById.Values
            .GroupBy(function => (function.ClassId, function.Name), ValueTupleComparer.OrdinalIgnoreCase)
            .ToDictionary(group => group.Key, group => group.First(), ValueTupleComparer.OrdinalIgnoreCase));

    public static string ClassName(int classId)
        => ClassNames.TryGetValue(classId, out var name) ? name : $"Class{classId}";

    public static GameCubeScriptFunctionInfo? Function(int classId, int functionId)
        => FunctionsById.TryGetValue((classId, functionId), out var function) ? function : null;

    public static string FunctionDisplayName(int classId, int functionId)
    {
        var function = Function(classId, functionId);
        return function is null
            ? $"class_{classId}.function_{functionId}"
            : classId == 0 ? function.Name : function.QualifiedName;
    }

    public static string FunctionComment(int classId, int functionId)
    {
        var function = Function(classId, functionId);
        if (function is null)
        {
            return string.Empty;
        }

        var details = new List<string> { function.LegacyName, $"params={function.ParameterCount}" };
        if (!string.IsNullOrWhiteSpace(function.ReturnType))
        {
            details.Add($"returns={function.ReturnType}");
        }

        if (!string.IsNullOrWhiteSpace(function.ParameterTypes))
        {
            details.Add($"types={function.ParameterTypes}");
        }

        if (!string.IsNullOrWhiteSpace(function.Hint))
        {
            details.Add(function.Hint);
        }

        return string.Join("; ", details);
    }

    public static bool TryResolveClassFunction(string text, out int classId, out int functionId)
    {
        classId = 0;
        functionId = 0;
        text = text.Trim().TrimEnd(';');
        if (text.Length == 0)
        {
            return false;
        }

        var parts = text.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        if (parts.Length == 1)
        {
            if (TryResolveFunctionName(0, parts[0], out functionId))
            {
                classId = 0;
                return true;
            }

            return false;
        }

        return parts.Length == 2
            && TryResolveClassName(parts[0], out classId)
            && TryResolveFunctionName(classId, parts[1], out functionId);
    }

    private static bool TryResolveClassName(string text, out int classId)
    {
        classId = 0;
        if (ClassIdsByName.TryGetValue(text, out classId))
        {
            return true;
        }

        return TryParsePrefixedIndex(text, "class_", out classId)
            || TryParsePrefixedIndex(text, "Class", out classId)
            || int.TryParse(text, out classId);
    }

    private static bool TryResolveFunctionName(int classId, string text, out int functionId)
    {
        functionId = 0;
        if (FunctionsByName.TryGetValue((classId, text), out var function))
        {
            functionId = function.FunctionId;
            return true;
        }

        return TryParsePrefixedIndex(text, "function_", out functionId)
            || TryParsePrefixedIndex(text, "function", out functionId)
            || int.TryParse(text, out functionId);
    }

    private static bool TryParsePrefixedIndex(string text, string prefix, out int value)
    {
        value = 0;
        return text.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)
            && int.TryParse(text[prefix.Length..], out value);
    }

    private sealed class ValueTupleComparer : IEqualityComparer<(int ClassId, string FunctionName)>
    {
        public static ValueTupleComparer OrdinalIgnoreCase { get; } = new();

        public bool Equals((int ClassId, string FunctionName) x, (int ClassId, string FunctionName) y)
            => x.ClassId == y.ClassId && StringComparer.OrdinalIgnoreCase.Equals(x.FunctionName, y.FunctionName);

        public int GetHashCode((int ClassId, string FunctionName) obj)
            => HashCode.Combine(obj.ClassId, StringComparer.OrdinalIgnoreCase.GetHashCode(obj.FunctionName));
    }
}

