namespace CipherSnagemEditor.XD;

public sealed record XdTrainerRecord(
    int Index,
    string DeckName,
    string Name,
    string ClassName,
    int ClassId,
    int ModelId,
    int Ai,
    int NameId,
    int FirstPokemonIndex,
    int PreBattleTextId,
    int VictoryTextId,
    int DefeatTextId,
    int CameraEffects,
    string Location,
    bool HasShadow,
    IReadOnlyList<XdTrainerPokemonRecord> Pokemon);

public sealed record XdTrainerPokemonRecord(
    int Slot,
    int DeckIndex,
    int SpeciesId,
    string SpeciesName,
    int Level,
    int ShadowId,
    int ItemId,
    string ItemName,
    int Ability,
    int Nature,
    int Gender,
    int Happiness,
    int Iv,
    IReadOnlyList<int> Evs,
    IReadOnlyList<int> MoveIds,
    IReadOnlyList<string> MoveNames,
    XdShadowPokemonRecord? ShadowData);

public sealed record XdShadowPokemonRecord(
    int Index,
    int StoryPokemonIndex,
    int SpeciesId,
    string SpeciesName,
    int Level,
    int CatchRate,
    int HeartGauge,
    int InUseFlag,
    int FleeValue,
    int Aggression,
    int AlwaysFlee,
    IReadOnlyList<int> MoveIds,
    IReadOnlyList<string> MoveNames,
    int ShadowBoostLevel,
    int ItemId,
    string ItemName,
    int Ability,
    string AbilityName,
    int Nature,
    int Gender,
    int Happiness,
    int Iv,
    IReadOnlyList<int> Evs,
    IReadOnlyList<int> RegularMoveIds,
    IReadOnlyList<string> RegularMoveNames);

public sealed record XdPokemonStatsRecord(
    int Index,
    int StartOffset,
    string Name,
    int NameId,
    int NationalIndex,
    int ExpRate,
    int GenderRatio,
    int BaseExp,
    int BaseHappiness,
    double Height,
    double Weight,
    int Type1,
    string Type1Name,
    int Type2,
    string Type2Name,
    int Ability1,
    int Ability2,
    int HeldItem1,
    string HeldItem1Name,
    int HeldItem2,
    string HeldItem2Name,
    int CatchRate,
    int Hp,
    int Attack,
    int Defense,
    int SpecialAttack,
    int SpecialDefense,
    int Speed,
    int HpYield,
    int AttackYield,
    int DefenseYield,
    int SpecialAttackYield,
    int SpecialDefenseYield,
    int SpeedYield,
    IReadOnlyList<bool> LearnableTms,
    IReadOnlyList<XdLevelUpMoveRecord> LevelUpMoves,
    IReadOnlyList<XdEvolutionRecord> Evolutions);

public sealed record XdLevelUpMoveRecord(int Level, int MoveId, string MoveName);

public sealed record XdEvolutionRecord(int Method, int Condition, int EvolvedSpeciesId, string EvolvedSpeciesName);

public sealed record XdMoveRecord(
    int Index,
    int StartOffset,
    string Name,
    int NameId,
    string Description,
    int DescriptionId,
    int TypeId,
    string TypeName,
    int TargetId,
    int CategoryId,
    int AnimationId,
    int Animation2Id,
    int EffectId,
    int EffectTypeId,
    int Power,
    int Accuracy,
    int Pp,
    int Priority,
    int EffectAccuracy,
    bool HmFlag,
    bool SoundBasedFlag,
    bool ContactFlag,
    bool KingsRockFlag,
    bool ProtectFlag,
    bool SnatchFlag,
    bool MagicCoatFlag,
    bool MirrorMoveFlag,
    bool IsShadow);

public sealed record XdItemRecord(
    int Index,
    int StartOffset,
    string Name,
    int NameId,
    string Description,
    int DescriptionId,
    int BagSlotId,
    bool CanBeHeld,
    int Price,
    int CouponPrice,
    int Parameter,
    int HoldItemId,
    int InBattleUseId,
    IReadOnlyList<int> FriendshipEffects);

public sealed record XdTypeRecord(
    int Index,
    int StartOffset,
    string Name,
    int NameId,
    int CategoryId,
    IReadOnlyList<int> Effectiveness);

public sealed record XdTreasureRecord(
    int Index,
    int StartOffset,
    int ModelId,
    int Quantity,
    int Angle,
    int RoomId,
    string RoomName,
    int Flag,
    int ItemId,
    string ItemName,
    float X,
    float Y,
    float Z);

public sealed record XdPokespotRecord(
    int Index,
    string SpotName,
    int SpeciesId,
    string SpeciesName,
    int MinLevel,
    int MaxLevel,
    int EncounterPercentage,
    int StepsPerSnack,
    int StartOffset);
